-- AlterTable
ALTER TABLE "Season" ADD COLUMN     "missionsEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "missionsStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "whitelist" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
